/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'

export type LzAccountAlt = {
  indexOrPubkey: number[] /* size: 32 */
  isSigner: boolean
  isWritable: boolean
  isAltIndex: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const lzAccountAltBeet = new beet.BeetArgsStruct<LzAccountAlt>(
  [
    ['indexOrPubkey', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['isSigner', beet.bool],
    ['isWritable', beet.bool],
    ['isAltIndex', beet.bool],
  ],
  'LzAccountAlt'
)
