[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
endpoint = "6xmPjYnXyxz36xcKkv2zCrZc72LK5hQ9xzY3EjeZ59MV"
governance = "EiQujD3MpwhznKZn4jSa9J7j6cHd7W9QA213QrPZgpR3"
oft = "G2BYTnfGCMQAErMZkTBCFSapKevzf6QCjizjXi8hFEtJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"

[test]
upgradeable = true