use crate::msg_codec::{msg_codec, GovernanceMessage};
use crate::*;
use oapp::endpoint_cpi::{get_accounts_for_clear, LzAccount};
use oapp::{endpoint::ID as ENDPOINT_ID, LzReceiveParams};
/// LzReceiveTypes instruction provides a list of accounts that are used in the LzReceive
/// instruction. The list of accounts required by this LzReceiveTypes instruction can be found
/// from the specific PDA account that is generated by the LZ_RECEIVE_TYPES_SEED.
#[derive(Accounts)]
pub struct LzReceiveTypes<'info> {
    #[account(seeds = [GOVERNANCE_SEED, &governance.id.to_be_bytes()], bump = governance.bump)]
    pub governance: Account<'info, Governance>,
}

impl LzReceiveTypes<'_> {
    /// The list of accounts should follow the rules below:
    /// 1. Include all the accounts that are used in the LzReceive instruction, including the
    /// accounts that are used by the Endpoint program.
    /// 2. Set the account is a signer with ZERO address if the LzReceive instruction needs a payer
    /// to pay fee, like rent.
    /// 3. Set the account is writable if the LzReceive instruction needs to modify the account.
    pub fn apply(
        ctx: &Context<LzReceiveTypes>,
        params: &LzReceiveParams,
    ) -> Result<Vec<LzAccount>> {
        // There are two accounts that are used in the LzReceive instruction,
        // except those accounts for endpoint program.
        // The first account is the count account, that is the fixed one.
        let governance = ctx.accounts.governance.key();

        // The second account is the remote account, we find it by the params.src_eid.
        let seeds = [
            REMOTE_SEED,
            &governance.to_bytes(),
            &params.src_eid.to_be_bytes(),
        ];
        let (remote, _) = Pubkey::find_program_address(&seeds, ctx.program_id);

        let governance_message: GovernanceMessage = msg_codec::decode_governance(&params.message)?;

        // accounts 0..4
        let mut accounts = vec![
            // payer
            LzAccount {
                pubkey: Pubkey::default(),
                is_signer: true,
                is_writable: true,
            }, // 0
            // governance
            LzAccount {
                pubkey: governance,
                is_signer: false,
                is_writable: true,
            },
            // remote
            LzAccount {
                pubkey: remote,
                is_signer: false,
                is_writable: false,
            },
            // program
            LzAccount {
                pubkey: governance_message.program_id,
                is_signer: false,
                is_writable: false,
            },
            // system program
            LzAccount {
                pubkey: solana_program::system_program::ID,
                is_signer: false,
                is_writable: false,
            },
        ];

        // accounts 5..12
        // append the accounts for the clear ix
        let accounts_for_clear = get_accounts_for_clear(
            ENDPOINT_ID,
            &governance,
            params.src_eid,
            &params.sender,
            params.nonce,
        );
        accounts.extend(accounts_for_clear);

        // accounts 13..
        // Add gov msg accounts individually
        accounts.extend(
            governance_message
                .accounts
                .iter()
                .filter(|acc| {
                    acc.pubkey != OWNER_PLACEHOLDER
                        && acc.pubkey != PAYER_PLACEHOLDER
                        && acc.pubkey != governance_message.program_id
                })
                .map(|acc| LzAccount {
                    pubkey: acc.pubkey,
                    is_signer: acc.is_signer,
                    is_writable: acc.is_writable,
                }),
        );

        Ok(accounts)
    }
}
