// Converts Solana VersionedTransactions (from JSON) into GovernanceMessages.
//
// Usage:
//   cargo run -p convert-txs -- <txs.json>
//
// The JSON file should contain an array of objects with the format:
//   [{ "point": { "eid": u32, "address": "..." }, "data": "<hex>", "description": "..." }]
//
// For each Solana transaction (identified by point.eid), the tool:
//   1. Deserializes the hex data as a Solana legacy Message
//   2. Extracts each instruction
//   3. Replaces occurrences of HARDCODED_CPI_ACCOUNT with CPI_AUTHORITY_PLACEHOLDER
//   4. Builds and encodes a GovernanceMessage for each instruction
//
// origin_caller is NOT set here -- GovernanceOAppSender handles that on-chain.

use std::str::FromStr;

use base64::Engine;
use governance::msg_codec::{Acc, GovernanceMessage};
use governance::CPI_AUTHORITY_PLACEHOLDER;
use solana_sdk::instruction::{AccountMeta, Instruction};
use solana_sdk::message::Message;
use solana_sdk::pubkey::Pubkey;
use solana_sdk::transaction::Transaction;

/// The account address to replace with CPI_AUTHORITY_PLACEHOLDER in every instruction.
const HARDCODED_CPI_ACCOUNT: &str = "AYPtjx4Hc8us1ikULUedkmZ3wtiD6tmL7gK3qe4V3oHt";

/// Default payer used when building simulation transactions.
/// You can replace it with any address with SOL
const DEFAULT_PAYER: &str = "6Xu7SvWnBr1vo7Vst3cRZf2TW46PJxyZnNiv89RMMFuS";

#[derive(serde::Deserialize)]
struct TxEntry {
    point: Point,
    data: String,
    #[serde(default)]
    description: Option<String>,
}

#[derive(serde::Deserialize)]
struct Point {
    eid: u32,
    address: String,
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: {} <txs.json>", args[0]);
        eprintln!();
        eprintln!("Arguments:");
        eprintln!("  txs.json - JSON file containing Solana transactions generated by devtools");
        std::process::exit(1);
    }

    let file_path = &args[1];

    // -- Read & parse JSON ------------------------------------------------

    let json_data = std::fs::read_to_string(file_path).unwrap_or_else(|e| {
        eprintln!("Failed to read {}: {}", file_path, e);
        std::process::exit(1);
    });

    let entries: Vec<TxEntry> = serde_json::from_str(&json_data).unwrap_or_else(|e| {
        eprintln!("Failed to parse JSON: {}", e);
        std::process::exit(1);
    });

    // -- Resolve constants ------------------------------------------------

    let hardcoded_cpi_account = Pubkey::from_str(HARDCODED_CPI_ACCOUNT).expect("Invalid HARDCODED_CPI_ACCOUNT");
    let payer = Pubkey::from_str(DEFAULT_PAYER).expect("Invalid DEFAULT_PAYER");

    eprintln!("Hardcoded CPI account to replace : {}", HARDCODED_CPI_ACCOUNT);
    eprintln!("CPI_AUTHORITY_PLACEHOLDER         : {}", CPI_AUTHORITY_PLACEHOLDER);
    eprintln!();

    const SOLANA_EIDS: &[u32] = &[30168, 40168];

    for (i, entry) in entries.iter().enumerate() {
        // Only process Solana transactions (identified by point.eid)
        if !SOLANA_EIDS.contains(&entry.point.eid) {
            eprintln!("Skipping entry #{} (eid {} is not a Solana eid)", i, entry.point.eid);
            continue;
        }

        let desc = entry
            .description
            .as_deref()
            .unwrap_or("(no description)");
        println!("=== Entry #{}: {} ===", i, desc);
        println!(
            "  Point: eid={}, address={}",
            entry.point.eid, entry.point.address
        );

        let msg_bytes = match hex::decode(&entry.data) {
            Ok(b) => b,
            Err(e) => {
                eprintln!("  Failed to decode hex for entry #{}: {}", i, e);
                continue;
            }
        };

        if msg_bytes.is_empty() {
            eprintln!("  Empty data, skipping");
            continue;
        }

        // Check the version byte – high bit set means V0/versioned message
        if msg_bytes[0] & 0x80 != 0 {
            eprintln!("  Skipping: V0/versioned messages are not yet supported");
            continue;
        }

        // Deserialize as a legacy Solana Message (wire format == bincode with short_vec)
        let message: Message = match bincode::deserialize(&msg_bytes) {
            Ok(m) => m,
            Err(e) => {
                eprintln!("  Failed to deserialize Message for entry #{}: {}", i, e);
                continue;
            }
        };

        let account_keys = &message.account_keys;

        eprintln!("  Account keys ({}):", account_keys.len());
        for (k, key) in account_keys.iter().enumerate() {
            let marker = if *key == hardcoded_cpi_account {
                " <-- HARDCODED_CPI_ACCOUNT (will be replaced)"
            } else {
                ""
            };
            eprintln!("    [{}] {}{}", k, key, marker);
        }
        eprintln!();

        // -- Extract instructions and build GovernanceMessages ----------------

        for (j, ix) in message.instructions.iter().enumerate() {
            let gov_msg = compiled_ix_to_governance_message(
                &message,
                ix,
                &hardcoded_cpi_account,
            );

            println!("  --- Instruction #{} ---", j);
            println!("  Program: {}", gov_msg.program_id);

            for (k, acc) in gov_msg.accounts.iter().enumerate() {
                let marker = if acc.pubkey == CPI_AUTHORITY_PLACEHOLDER {
                    " [CPI_AUTHORITY_PLACEHOLDER]"
                } else {
                    ""
                };
                println!(
                    "    Account[{}]: {} (signer={}, writable={}){}",
                    k, acc.pubkey, acc.is_signer, acc.is_writable, marker
                );
            }

            println!("  Instruction data (hex): {}", hex::encode(&gov_msg.data));

            // -- Encode GovernanceMessage body (for EVM governance call) -------

            let mut body_buf = Vec::new();
            gov_msg.write_body(&mut body_buf).unwrap();
            println!();
            println!("  dstTarget   : {}", hex::encode(gov_msg.program_id.to_bytes()));
            println!("  dstCallData : {}", hex::encode(&body_buf));

            // -- Simulation transaction ----------------------------------------
            // Replace CPI_AUTHORITY_PLACEHOLDER back with the original account
            // so the transaction can be simulated on-chain.

            let sim_tx = Transaction::new_with_payer(
                &[Instruction {
                    program_id: gov_msg.program_id,
                    accounts: gov_msg
                        .accounts
                        .iter()
                        .map(|a| AccountMeta {
                            pubkey: if a.pubkey == CPI_AUTHORITY_PLACEHOLDER {
                                hardcoded_cpi_account
                            } else {
                                a.pubkey
                            },
                            is_signer: a.is_signer,
                            is_writable: a.is_writable,
                        })
                        .collect(),
                    data: gov_msg.data.clone(),
                }],
                Some(&payer),
            );

            println!(
                "  Simulation (base64): {}",
                base64::engine::general_purpose::STANDARD.encode(sim_tx.message_data())
            );
            println!();
        }

        println!();
    }
}
// ---------------------------------------------------------------------------
// Core conversion logic (extracted for testability)
// ---------------------------------------------------------------------------

/// Convert a single compiled instruction (from a deserialized Solana Message)
/// into a GovernanceMessage, replacing `replace_pubkey` with CPI_AUTHORITY_PLACEHOLDER.
fn compiled_ix_to_governance_message(
    message: &Message,
    ix: &solana_sdk::instruction::CompiledInstruction,
    replace_pubkey: &Pubkey,
) -> GovernanceMessage {
    let account_keys = &message.account_keys;
    let program_id = account_keys[ix.program_id_index as usize];

    let accounts: Vec<Acc> = ix
        .accounts
        .iter()
        .map(|&idx| {
            let idx = idx as usize;
            let pubkey = account_keys[idx];
            let replaced = pubkey == *replace_pubkey;
            Acc {
                pubkey: if replaced {
                    CPI_AUTHORITY_PLACEHOLDER
                } else {
                    pubkey
                },
                is_signer: message.is_signer(idx),
                is_writable: message.is_writable(idx),
            }
        })
        .collect();

    GovernanceMessage {
        origin_caller: [0u8; 32], // set by GovernanceOAppSender on-chain
        program_id,
        accounts,
        data: ix.data.clone(),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_encoding() {
        let memo_program =
            Pubkey::from_str("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr").unwrap();
        let payer =
            Pubkey::from_str("6Xu7SvWnBr1vo7Vst3cRZf2TW46PJxyZnNiv89RMMFuS").unwrap();
        let hardcoded = Pubkey::from_str(HARDCODED_CPI_ACCOUNT).unwrap();
        let data = "✩₊˚.⋆☾⋆⁺₊✧".as_bytes().to_vec();

        // Generated using: GOVERNANCE_ID=SKYGRikJcGSa3jC5HDyzDrVsmkCk3e5SqAurycny8PW cargo test -p governance --test msg_codec -- --exact --show-output test_msg_codec::test_hello_world
        let expected_target = "054a535a992921064d24e87160da387c7c35b5ddbc92bb81e41fa8404105448d";
        let expected_call_data = "0000e29ca9e2828acb9a2ee28b86e298bee28b86e281bae2828ae29ca7";

        // -- Actual: Solana Message -> serialize -> deserialize -> pipeline -------
        let solana_msg = Message::new(
            &[Instruction {
                program_id: memo_program,
                accounts: vec![],
                data: data,
            }],
            Some(&payer),
        );
        let wire = bincode::serialize(&solana_msg).unwrap();
        let deser: Message = bincode::deserialize(&wire).unwrap();

        let gov_msg = compiled_ix_to_governance_message(
            &deser,
            &deser.instructions[0],
            &hardcoded,
        );

        let mut actual_body = Vec::new();
        gov_msg.write_body(&mut actual_body).unwrap();
        let actual_target = hex::encode(gov_msg.program_id.to_bytes());
        let actual_call_data = hex::encode(&actual_body);

        // -- Assert exact match --------------------------------------------------
        assert_eq!(actual_target, expected_target, "dstTarget mismatch");
        assert_eq!(actual_call_data, expected_call_data, "dstCallData mismatch");
    }

    /// Verifies that HARDCODED_CPI_ACCOUNT is replaced with
    /// CPI_AUTHORITY_PLACEHOLDER and the resulting encoding matches
    /// a GovernanceMessage built with the placeholder directly.
    #[test]
    fn test_cpi_authority_replacement_encoding() {
        // Use an arbitrary program (not a builtin) so is_writable is not demoted.
        let program_id =
            Pubkey::from_str("627tpP7taNoCC2CvcV5qcftsVftpaeGiP78tyNEQoNLt").unwrap();
        let payer =
            Pubkey::from_str("6Xu7SvWnBr1vo7Vst3cRZf2TW46PJxyZnNiv89RMMFuS").unwrap();
        let hardcoded = Pubkey::from_str(HARDCODED_CPI_ACCOUNT).unwrap();
        let other_account =
            Pubkey::from_str("HC8D1rWMtAifPRhUYD7PwKHMtMVLtwCjarfNVvcN3SGK").unwrap();
        let data = vec![0xCA, 0xFE];

        // -- Build a Solana Message where hardcoded is a writable signer ----------
        let solana_msg = Message::new(
            &[Instruction {
                program_id,
                accounts: vec![
                    AccountMeta::new(hardcoded, true),       // signer + writable
                    AccountMeta::new(other_account, false),   // writable, not signer
                ],
                data: data.clone(),
            }],
            Some(&payer),
        );
        let wire = bincode::serialize(&solana_msg).unwrap();
        let deser: Message = bincode::deserialize(&wire).unwrap();

        let gov_msg = compiled_ix_to_governance_message(
            &deser,
            &deser.instructions[0],
            &hardcoded,
        );

        // -- The hardcoded account must now be CPI_AUTHORITY_PLACEHOLDER ----------
        assert_eq!(
            gov_msg.accounts[0].pubkey, CPI_AUTHORITY_PLACEHOLDER,
            "First account should be CPI_AUTHORITY_PLACEHOLDER"
        );
        assert!(gov_msg.accounts[0].is_signer);
        assert!(gov_msg.accounts[0].is_writable);

        // -- The other account must be unchanged ----------------------------------
        assert_eq!(gov_msg.accounts[1].pubkey, other_account);

        // -- Encoding must match a directly-built GovernanceMessage ----------------
        let expected = GovernanceMessage {
            origin_caller: [0u8; 32],
            program_id,
            accounts: vec![
                Acc { pubkey: CPI_AUTHORITY_PLACEHOLDER, is_signer: true, is_writable: true },
                Acc { pubkey: other_account, is_signer: false, is_writable: true },
            ],
            data: data,
        };

        let mut actual_body = Vec::new();
        gov_msg.write_body(&mut actual_body).unwrap();
        let mut expected_body = Vec::new();
        expected.write_body(&mut expected_body).unwrap();

        assert_eq!(
            hex::encode(gov_msg.program_id.to_bytes()),
            hex::encode(expected.program_id.to_bytes()),
            "dstTarget mismatch"
        );
        assert_eq!(
            hex::encode(&actual_body),
            hex::encode(&expected_body),
            "dstCallData mismatch"
        );
    }

    /// Mirror of test_spl_token_transfer from programs/governance/tests/msg_codec.rs.
    ///
    /// Builds an SPL Token TransferChecked instruction with the real CPI
    /// authority as the owner/signer, runs it through the pipeline (which
    /// replaces it with CPI_AUTHORITY_PLACEHOLDER), and asserts the encoded
    /// output is byte-identical to the governance test suite.
    #[test]
    fn test_spl_token_transfer_encoding() {
        // Generated using:
        // GOVERNANCE_ID=SKYGRikJcGSa3jC5HDyzDrVsmkCk3e5SqAurycny8PW cargo test -p governance --test msg_codec -- --exact --show-output test_msg_codec::test_spl_token_transfer
        let expected_target = "06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a9";
        let expected_call_data = "0004\
            e1c50679ce41b750687dd3aba8c0542b2f24e8b3c1dfbb65e083a00894413ddf0001\
            f09487642c4d2af896c0a30072c237dfbec45c3c504e5cc0e00621f3b420b5bc0000\
            351d1961aca4539c1ac437655e391ecc2a57772e05d38d0aa012860cabc44ade0001\
            6370695f617574686f726974790000000000000000000000000000000000000001000c\
            0a0000000000000009";

        let hardcoded = Pubkey::from_str(HARDCODED_CPI_ACCOUNT).unwrap();
        let payer = Pubkey::from_str(DEFAULT_PAYER).unwrap();
        let spl_token_program =
            Pubkey::from_str("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA").unwrap();
        let mint =
            Pubkey::from_str("HC8D1rWMtAifPRhUYD7PwKHMtMVLtwCjarfNVvcN3SGK").unwrap();
        // Associated token address derived from the real CPI authority
        // (printed by the governance test: "Associated token address: GCJyy1ZQ...")
        let associated_token =
            Pubkey::from_str("GCJyy1ZQjDhRL7jpbJfxEKhcwv2Gxxv7ZpbxEfazGit6").unwrap();
        let destination =
            Pubkey::from_str("4aLLvFDsgPsz7WXWgAEVPXJ4Kpczbb2z8uPW4Aca2r1b").unwrap();

        // TransferChecked { amount: 10, decimals: 9 }.pack()
        let instruction_data = hex::decode("0c0a0000000000000009").unwrap();

        // Build Solana instruction with the real CPI authority as owner/signer.
        // The pipeline will replace it with CPI_AUTHORITY_PLACEHOLDER.
        let ix = Instruction {
            program_id: spl_token_program,
            accounts: vec![
                AccountMeta::new(associated_token, false),  // source ATA (writable)
                AccountMeta::new_readonly(mint, false),     // mint (readonly)
                AccountMeta::new(destination, false),       // destination (writable)
                AccountMeta::new_readonly(hardcoded, true), // owner (readonly signer)
            ],
            data: instruction_data,
        };

        let solana_msg = Message::new(&[ix], Some(&payer));
        let wire = bincode::serialize(&solana_msg).unwrap();
        let deser: Message = bincode::deserialize(&wire).unwrap();

        let gov_msg = compiled_ix_to_governance_message(
            &deser,
            &deser.instructions[0],
            &hardcoded,
        );

        // -- Verify the replacement happened correctly ----------------------------
        let owner_acc = gov_msg.accounts.iter().find(|a| a.pubkey == CPI_AUTHORITY_PLACEHOLDER);
        assert!(owner_acc.is_some(), "CPI_AUTHORITY_PLACEHOLDER not found in accounts");
        let owner_acc = owner_acc.unwrap();
        assert!(owner_acc.is_signer, "owner should be a signer");
        assert!(!owner_acc.is_writable, "owner should NOT be writable");

        // -- Assert exact match against governance test output --------------------
        let mut actual_body = Vec::new();
        gov_msg.write_body(&mut actual_body).unwrap();
        let actual_target = hex::encode(gov_msg.program_id.to_bytes());
        let actual_call_data = hex::encode(&actual_body);

        assert_eq!(actual_target, expected_target, "dstTarget mismatch");
        assert_eq!(actual_call_data, expected_call_data, "dstCallData mismatch");
    }
}
